# This is an example goreleaser.yaml file with some sane defaults.
builds:
- binary: "{{ .ProjectName }}_{{ .Tag }}"
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
archives:
- name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
checksum:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
snapshot:
  name_template: "terraform-provider-azuredevops"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: microsoft
    name: terraform-provider-azuredevops
